name: USBSI
favicon: null
layout_spectrum: 1
typography_spectrum: 0.63959
title: Testing for USBSI
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#014c8d'
    - '#5b88b2'
    - '#020202'
    - '#a2caed'
    - '#d01e45'
  brandStrength: 0.5
  lightness: 0.12107194005511701
  saturation: 0.4375
  rhythmicContrast: 0.42901386227458715
purpose: []
